import os
import sys

sys.path.append(os.environ.get("HIPPYLIB_PATH"))
import argparse
from typing import Tuple

import hippylib as hp
import numpy as np

################################################################################

parser = argparse.ArgumentParser()

parser.add_argument(
    "-PDEproblem_base_dir",
    "--PDEproblem_base_dir",
    type=str,
    default="/workspace/josh/dinox/examples/",
    help="Folder where PDE Problems are stored",
)
parser.add_argument(
    "-BIP_problem_dir",
    "--BIP_problem_dir",
    type=str,
    default="/storage/joshua/nonlinear_diffusion_reaction/problem/rel_noise_0.01_noise_stdev_0.009724453175183136/",
    help="Problem folder",
)
parser.add_argument("-BIP", "--BIP", type=int, default=0, help="One of [0,1,2,3]")

args = parser.parse_args()


def load_one_of_4_BIPs(PDEproblem_dir: str, BIPproblem_dir: str, BIP: int) -> Tuple:
    """Load one of the 4 BIPs generated by randomly_pick_4_BIPs.py

    This function loads up a BIP (a hippylib.model). What this means is that
    it all the associated information is loaded from disk, including the specific
    BIP data realization (for the correct misfit/likelihood function), the associated
    noise standard deviation (given that this data was generated synthetically) and
    the targets/locations to be used by the PointwiseObservationOperator.

    Parameters
    ----------
    PDEproblem_dir: str
        String of the directory where all PDE problems are located: e.g. /workspace/josh/dinox/examples/
    BIPproblem_dir: str
        String of the specific BIP directory to load up one of 4 BIPs from:
        e.g. /storage/joshua/nonlinear_diffusion_reaction/problem/rel_noise_0.01_noise_stdev_0.009724453175183136/
    BIP: int
        One of [0, 1,2,3] specifying the specific BIP to load up. (In otherwords, the specific
        random data that was pre-synthetically generated.)
    """
    problem_name = BIPproblem_dir.split("/problem/")[0].split("/")[-1]
    sys.path.append(PDEproblem_dir)
    import importlib

    model_module = importlib.import_module(problem_name + ".model")
    settings = model_module.settings()
    ################################################################################
    # Set up the model
    settings["output_path"] = None
    noise_stdev = np.load(BIPproblem_dir + "likelihood/noise_stdev.npy")
    targets = np.load(BIPproblem_dir + "likelihood/observation_targets_coordinates.npy")
    settings["targets"] = targets  # override the randomly generated targets with the one we used, saved to disk.
    pde, prior, misfit, _, _ = model_module.model(settings)

    misfit.noise_variance = noise_stdev * noise_stdev  # set the noise variance read from file
    misfit.d.set_local(np.load(f"{BIPproblem_dir}BIP_data/true_Y_{BIP}.npy"))  # set the data read from file
    model = hp.Model(pde, prior, misfit)

    return model, np.load(
        f"{BIPproblem_dir}BIP_data/true_X_{BIP}.npy",
    )


model, true_m_np = load_one_of_4_BIPs(args.PDEproblem_base_dir, args.BIP_problem_dir, args.BIP)

print("\n", model)
